### ISSUE TITLE
v3有些代码没有被识别

### ISSUE THREAD

**Issue by CrystalRivern** [dragon-archer/paradox-highlight#3]
比如外交行动中的
first_modifier
add_overlord_lobby_appeasement_from_diplomacy

**Comment by dragon-archer** [comment]
v3最新的几个小版本加入的一些代码尚未更新进入

同时`first_modifier`等属性列表暂时没有找到批量拉取的办法，为纯手工整理，因此难免有所遗漏，欢迎发issue来查缺补漏

另外，`add_overlord_lobby_appeasement_from_diplomacy`并非游戏引擎原生`effect`而是定义于`common/scripted_effects/00_lobby_effects.txt`中的`scripted_effect`，本插件暂时还不支持对于自定义`scripted_effect`的高亮

**Comment by CrystalRivern** [comment]
原来是这样，谢谢大佬
